// <auto-generated />
using System;
using LuminaLibrary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuminaLibrary.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260704105553_AddBorrowStatusEnum")]
    partial class AddBorrowStatusEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuminaLibrary.Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nationality");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Biography = "Nhà văn hiện thực xuất sắc của văn học Việt Nam hiện đại",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nam Cao"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Biography = "Nữ nhà văn người Anh, tác giả bộ truyện Harry Potter nổi tiếng toàn cầu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "J.K. Rowling"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Biography = "Nhà báo, nhà văn người Anh nổi tiếng với tiểu thuyết Trại Súc Vật và 1984",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Biography = "Nhà văn, nhà thuyết trình người Mỹ, tác giả cuốn Đắc Nhân Tâm",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Dale Carnegie"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Biography = "Nhà văn Việt Nam nổi tiếng với truyện Dế Mèn Phiêu Lưu Ký",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Tô Hoài"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Biography = "Nhà vật lý lý thuyết, vũ trụ học nổi tiếng người Anh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Stephen Hawking"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Biography = "Nhà đầu tư, doanh nhân người Mỹ, nổi tiếng với bộ sách Cha Giàu Cha Nghèo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Robert Kiyosaki"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Biography = "Tác giả người Mỹ, một trong những người sáng lập ra thể loại thành công học",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Napoleon Hill"
                        });
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int")
                        .HasColumnName("available_copies");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("isbn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int")
                        .HasColumnName("published_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("publisher");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int")
                        .HasColumnName("total_copies");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AvailableCopies = 5,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tác phẩm hiện thực phê phán kinh điển mô tả số phận bi thảm của người nông dân nghèo trước Cách mạng.",
                            ISBN = "9786046903251",
                            IsDeleted = false,
                            PublishedYear = 1941,
                            Publisher = "NXB Văn Học",
                            Rating = 4.7999999999999998,
                            Title = "Chí Phèo",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AvailableCopies = 2,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tập đầu tiên trong bộ truyện giả tưởng đình đám về cậu bé phù thủy Harry Potter.",
                            ISBN = "9786045625442",
                            IsDeleted = false,
                            PublishedYear = 1997,
                            Publisher = "NXB Trẻ",
                            Rating = 4.9000000000000004,
                            Title = "Harry Potter và Hòn Đá Phù Thủy",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AvailableCopies = 2,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiểu thuyết phản địa đàng nổi tiếng mô tả một xã hội độc tài kiểm soát tư duy con người.",
                            ISBN = "9786045654329",
                            IsDeleted = false,
                            PublishedYear = 1949,
                            Publisher = "NXB Hội Nhà Văn",
                            Rating = 4.7000000000000002,
                            Title = "Một Chín Tám Tư (1984)",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AvailableCopies = 9,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cuốn sách nghệ thuật ứng xử nổi tiếng nhất mọi thời đại, giúp xây dựng mối quan hệ tốt đẹp.",
                            ISBN = "9786045883259",
                            IsDeleted = false,
                            PublishedYear = 1936,
                            Publisher = "NXB Tổng Hợp TP.HCM",
                            Rating = 4.9000000000000004,
                            Title = "Đắc Nhân Tâm",
                            TotalCopies = 10
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            AvailableCopies = 4,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Truyện viết cho thiếu nhi vô cùng xuất sắc về hành trình trưởng thành của chú Dế Mèn.",
                            ISBN = "9786042125345",
                            IsDeleted = false,
                            PublishedYear = 1941,
                            Publisher = "NXB Kim Đồng",
                            Rating = 4.5999999999999996,
                            Title = "Dế Mèn Phiêu Lưu Ký",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            AvailableCopies = 4,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tác phẩm trào phúng, mượn câu chuyện nông trại để châm biếm các vấn đề chính trị xã hội.",
                            ISBN = "9786049021235",
                            IsDeleted = false,
                            PublishedYear = 1945,
                            Publisher = "NXB Nhã Nam",
                            Rating = 4.5,
                            Title = "Trại Súc Vật",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            AvailableCopies = 2,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cuốn sách khoa học đại chúng bán chạy giải thích các khái niệm phức tạp của vật lý thiên văn.",
                            ISBN = "9786042188241",
                            IsDeleted = false,
                            PublishedYear = 1988,
                            Publisher = "NXB Trẻ",
                            Rating = 4.7999999999999998,
                            Title = "Lược Sử Thời Gian",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            AvailableCopies = 5,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cuốn sách dạy con về quản lý tài chính cá nhân và tư duy đầu tư làm giàu.",
                            ISBN = "9786043128912",
                            IsDeleted = false,
                            PublishedYear = 1997,
                            Publisher = "NXB Trẻ",
                            Rating = 4.7000000000000002,
                            Title = "Cha Giàu Cha Nghèo",
                            TotalCopies = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            AvailableCopies = 4,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cẩm nang hướng dẫn cách phát triển tư duy làm giàu và gặt hái thành công cá nhân.",
                            ISBN = "9786045892534",
                            IsDeleted = false,
                            PublishedYear = 1937,
                            Publisher = "NXB Tổng Hợp TP.HCM",
                            Rating = 4.9000000000000004,
                            Title = "Nghĩ Giàu và Làm Giàu",
                            TotalCopies = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            AvailableCopies = 1,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Truyện ngắn xuất sắc khắc họa cuộc sống khốn cùng và vẻ đẹp tâm hồn của người nông dân Việt Nam.",
                            ISBN = "9786049512391",
                            IsDeleted = false,
                            PublishedYear = 1943,
                            Publisher = "NXB Văn Học",
                            Rating = 4.7999999999999998,
                            Title = "Lão Hạc",
                            TotalCopies = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            AvailableCopies = 3,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tập hai trong hành trình phiêu lưu đầy kịch tính của Harry Potter tại trường Hogwarts.",
                            ISBN = "9786045625459",
                            IsDeleted = false,
                            PublishedYear = 1998,
                            Publisher = "NXB Trẻ",
                            Rating = 4.9000000000000004,
                            Title = "Harry Potter và Phòng Chứa Bí Mật",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            AvailableCopies = 3,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tác phẩm hiện thực sâu sắc lên án chế độ cũ bóp nghẹt tài năng và ước mơ con người.",
                            ISBN = "9786049512344",
                            IsDeleted = false,
                            PublishedYear = 1943,
                            Publisher = "NXB Văn Học",
                            Rating = 4.5999999999999996,
                            Title = "Đời Thừa",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            AvailableCopies = 5,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Câu chuyện thần kỳ về sự trỗi dậy mạnh mẽ của nền kinh tế và công nghệ Israel.",
                            ISBN = "9786045688220",
                            IsDeleted = false,
                            PublishedYear = 2009,
                            Publisher = "NXB Thế Giới",
                            Rating = 4.7000000000000002,
                            Title = "Quốc Gia Khởi Nghiệp",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            AvailableCopies = 8,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Những câu chuyện ngắn truyền cảm hứng và nghị lực sống phi thường cho người đọc.",
                            ISBN = "9786045889312",
                            IsDeleted = false,
                            PublishedYear = 2002,
                            Publisher = "NXB Tổng Hợp TP.HCM",
                            Rating = 4.7999999999999998,
                            Title = "Hạt Giống Tâm Hồn",
                            TotalCopies = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            AvailableCopies = 2,
                            CategoryId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CoverImageUrl = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=600",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cuốn sách mở ra góc nhìn sâu sắc và sinh động hơn về bức tranh vũ trụ rộng lớn.",
                            ISBN = "9786042188258",
                            IsDeleted = false,
                            PublishedYear = 2001,
                            Publisher = "NXB Trẻ",
                            Rating = 4.7999999999999998,
                            Title = "Vũ Trụ Trong Vỏ Hạt Dẻ",
                            TotalCopies = 2
                        });
                });

            modelBuilder.Entity("LuminaLibrary.Domain.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("book_authors");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000006"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000007"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000008"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000009"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000010"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000011"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000012"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000013"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000014"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            BookId = new Guid("b0000000-0000-0000-0000-000000000015"),
                            AuthorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("LuminaLibrary.Domain.BorrowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("borrow_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fine_amount");

                    b.Property<bool>("IsFinePaid")
                        .HasColumnType("bit")
                        .HasColumnName("is_fine_paid");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("return_date");

                    b.Property<Guid?>("ReturnedToUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("returned_to_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BookId");

                    b.HasIndex("ReturnedToUserId");

                    b.HasIndex("UserId");

                    b.ToTable("borrow_records");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các tác phẩm văn học nổi tiếng trong nước qua các thời kỳ",
                            Name = "Văn học Việt Nam"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiểu thuyết, truyện ngắn nước ngoài dịch sang tiếng Việt",
                            Name = "Văn học Nước ngoài"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sách nghiên cứu khoa học, công nghệ thông tin và toán học",
                            Name = "Khoa học & Công nghệ"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phát triển bản thân, kỹ năng mềm, tâm lý học ứng dụng",
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kiến thức tài chính, quản trị kinh doanh, khởi nghiệp",
                            Name = "Kinh tế & Đầu tư"
                        });
                });

            modelBuilder.Entity("LuminaLibrary.Domain.ClassRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassScheduleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("class_schedule_id");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("registration_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassScheduleId", "UserId")
                        .IsUnique();

                    b.ToTable("class_registrations");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("instructor");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.Property<int>("RegisteredCount")
                        .HasColumnType("int")
                        .HasColumnName("registered_count");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("class_schedules");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("registration_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("event_registrations");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<int>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("likes");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_reviews");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_schedules");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventSpeaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_speakers");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.LibrarianConsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("LibrarianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("librarian_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ticket_number");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("librarian_consultations");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.LibraryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Fee")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fee");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("long_description");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<int>("RegisteredCount")
                        .HasColumnType("int")
                        .HasColumnName("registered_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.MembershipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tier_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("membership_requests");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.PasswordResetToken", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("code");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.HasKey("Email");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("int")
                        .HasColumnName("queue_position");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("reservation_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Librarian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("LuminaLibrary.Domain.SpaceReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("SpaceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("space_type");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ticket_number");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("space_reservations");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("membership_tier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Book", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.BookAuthor", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminaLibrary.Domain.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.BorrowRecord", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuminaLibrary.Domain.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminaLibrary.Domain.User", "ReturnedToUser")
                        .WithMany()
                        .HasForeignKey("ReturnedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Book");

                    b.Navigation("ReturnedToUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.ClassRegistration", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.ClassSchedule", "ClassSchedule")
                        .WithMany()
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventRegistration", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.LibraryEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventReview", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.LibraryEvent", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventSchedule", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.LibraryEvent", "Event")
                        .WithMany("Schedule")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.EventSpeaker", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.LibraryEvent", "Event")
                        .WithMany("Speakers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.LibrarianConsultation", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.MembershipRequest", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.RefreshToken", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Reservation", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.SpaceReservation", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.User", b =>
                {
                    b.HasOne("LuminaLibrary.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LuminaLibrary.Domain.LibraryEvent", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Schedule");

                    b.Navigation("Speakers");
                });
#pragma warning restore 612, 618
        }
    }
}
